SELECT
    PLACE_TYPE.NAME AS PLACE_TYPE,
    AIRPLANE_PLACES.PLACE
FROM AIRPLANE_PLACES
INNER JOIN PLACE_TYPE
ON AIRPLANE_PLACES.PLACE_TYPE_ID = PLACE_TYPE.ID
INNER JOIN FLIGHT
ON AIRPLANE_PLACES.AIRPLANE_ID = FLIGHT.AIRPLANE_ID
WHERE FLIGHT.FLIGHT_NUMBER = ~ЗНАЧЕНИЕ_ТУТ~ AND AIRPLANE_PLACES.PLACE NOT IN (
    SELECT PLACE
    FROM PASSENGERS
    WHERE PASSENGERS.FLIGHT_NUMBER = ~ЗНАЧЕНИЕ_ТУТ~
)
ORDER BY TO_NUMBER(REGEXP_SUBSTR(PLACE, '\d+')), REGEXP_SUBSTR(PLACE, '^\D*')


INSERT INTO PASSENGERS (SURNAME, FIRST_NAME, PATRONYMIC, DOCUMENT_NUMBER, DOCUMENT_SERIES, FLIGHT_NUMBER, DEPARTURE_DATE, PLACE) VALUES ('Фамилия', 'Имя', 'Отчество', 'D1', 'S1', 'N1', TO_DATE('24/10/2020', 'DD/MM/YYYY'), 'A1');